def cargar_tienda(linea_usuario_int)

    print()
    print("              ⚜ MERCADO DE AVENTUREROS ⚜")
    print()
    print("        ✦ Los objetos de hoy ✦")
    print()
    print("    > 01 🧪  Poción de Vida")
    print("        « Una pequeña ayuda para seguir luchando »")
    print("        🪙 20 monedas")
    print()
    print("    > 02 ⚔️  Espada del Guerrero")
    print("        « El acero habla por quien sabe usarlo »")
    print("        🪙 200 monedas")
    print()
    print("    > 03 🛡️  Escudo del Guardián")
    print("        « Ningún golpe atravesará esta defensa »")
    print("        🪙 150 monedas")
    print()
    print("    > 04 🥾  Botas del Explorador")
    print("        « El camino no tendrá secretos »")
    print("        🪙 100 monedas")
    print()
    print()
    print("              ✦ ✧ ✦ MASCOTAS FANTASÍA ✦ ✧ ✦")
    print("        ✦ 💡 Las mascotas pueden acompañarte durante tus aventuras. ✦")
    print()
    print("    > 05 🐉  Dragón Bebé")
    print("        « Una criatura de poder legendario »")
    print("        🪙 500 monedas")
    print()
    print("    > 06 🦄  Unicornio")
    print("        « Una criatura mágica nacida de las estrellas »")
    print("        🪙 450 monedas")
    print()
    print("    > 07 🐈‍⬛✨  Gato Mágico")
    print("        « Una criatura misteriosa que trae buena fortuna »")
    print("        🪙 400 monedas")
    print()
    print()
    print("        💰 Monedas Totales:")
    print("        ❯ ¿Qué deseas comprar?")